### ISSUE TITLE
Creación de piezas necesarias.

### ISSUE THREAD

**Issue by MateoVelasquez** [MateoVelasquez/Nero_3Dprinter_304040#1]
- [x]  Creación de tornillos con su respectiva tuerca según la lista del archivo Materiales.xlsx.
- [x]  Fuente de poder
- [x]  Extrusor All-Metal   (Hotend)
- [x]  Corrección del diseño de motores
- [x] Diseño de placas de finales de carrera.

**Comment by MateoVelasquez** [comment]
Es necesario diseñar las piezas en 3D (holders) que soportaran los finales de carrera, pero para ello es importante primero que exista el .par del final de carrera.
Ya existen algunos diseños hechos en gradCAB.... pero es necesario corroborar sus medidas para ver si nos sirven: https://grabcad.com/library/endstop-mecanico-chave-fim-de-curso-1

**Comment by MateoVelasquez** [comment]
De la misma forma, es necesario diseñar el HotEnd... Ya hay algunos diseños en GradCAB. Nuevamente es necesario corroborar sus medidas para saber si podemos usarlo.
Algunos diseños existentes:
https://grabcad.com/library/creality-cr-10-hotend-2
https://grabcad.com/library/ender-3-hot-end-1
https://grabcad.com/library/microswiss-all-metal-hotend-1

**Comment by NicolasMolina24** [comment]
Guardadas piezas necesarias #1
